server:
  port: ${SERVER_PORT:8030}

keycloak:
  enabled: false
  configurationFile: ${KEYCLOAK_JSON_PATH:file:src/main/resources/keycloak.json}

spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/app
#    url: jdbc:postgresql://postgres:5432/app
    username: dev
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true